Small fix to Manual Runtime so it builds.
I am getting the following error when building the previous version:

/home/ben/Artemis/artemis-code/src/runtime/toplevel/manualruntime.cpp:30: error: no matching function for call to 'artemis::ManualRuntime::connect(artemis::ArtemisWebViewPtr&, const char [12], artemis::ManualRuntime* const, const char [19])'